//@ sourceMappingURL=hello.js.map
// Generated by CoffeeScript 2.0.0-dev
void function () {
  var sayHi;
  sayHi = function (name) {
    console.log('Hello JSSummit!');
    return console.log('' + name + '!');
  };
  sayHi('Brandon');
}.call(this);